### ISSUE TITLE
Singularity images unavailable

### ISSUE THREAD

**Issue by susheelbhanu** [metashot/prok-quality#1]
Hi, 

I'm trying to do a test run using `singularity` since your documentation states as such. However, I'm getting the below error:

```
nextflow run metashot/prok-quality -c nextflow.config --genomes '*.fa' --outdir results -with-singularity

N E X T F L O W  ~  version 21.10.0
Launching `metashot/prok-quality` [angry_franklin] - revision: cdde065b32 [master]
You have requested to run with Singularity but no image were specified
```

My config has the following lines:
```
/* Singularity options */
singularity.enabled = true
singularity.autoMounts = true
```

It looks like the appropriate singularity images are not available. Could you please update/provide them?

Thank you!

**Comment by davidealbanese** [comment]
Dear @susheelbhanu, 

1. Modify your config file with:
    ```
    docker.enabled = false
    singularity.enabled = true
    singularity.autoMounts = true
    ```
2. Run the command without `-with-singularity`:
    ```
    nextflow run metashot/prok-quality -c nextflow.config --genomes '*.fa' --outdir results
   ```

**Comment by susheelbhanu** [comment]
Thanks a lot @davidealbanese. That seems to have done the trick. It is at least running! 🙏🏽
